# Generated by Django 4.2.2 on 2023-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_client_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
