# Generated by Django 4.2.2 on 2023-06-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_client_lat_client_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
