name: apptrix_dating
on: [push]
jobs:
  deploy_application:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          source: 'docker-compose.yaml,images'
          target: '/home/apptrix_dating'
      - name: run application
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/sky_parser            
            echo ${{secrets.PASSWORD}} | sudo -S docker compose down
            echo ${{secrets.PASSWORD}} | sudo -S docker compose up -d --build
